services:
  ferrecontrol_mysql_local:
    image: mysql:8.0
    container_name: ferrecontrol_mysql_local
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ferrecontrol_db
      MYSQL_USER: ferrecontrol_user
      MYSQL_PASSWORD: ferrecontrol_pass
      MYSQL_ROOT_PASSWORD: ferrecontrol_root_pass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ferrecontrol_mysql_data_local:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ferrecontrol_local_net

volumes:
  ferrecontrol_mysql_data_local:

networks:
  ferrecontrol_local_net:
    driver: bridge